version: '3.3'

services:
  redis:
    image: redis:5.0.5-alpine
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      infra:

  mongo:
    image: mongo:4
    container_name: mongo
    volumes:
      - /home/${USER}/.iio/infra/mongo:/data/db
    ports:
      - "40000:27017"
    networks:
      infra:

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - /home/${USER}/.iio/infra/minio/data:/data
      - /home/${USER}/.iio/infra/minio/config:/root/.minio
    ports:
      - "9000:9000"
    command: server /data
    networks:
      infra:

volumes:
  redis-data:

networks:
  infra:
    external: true
