version: '3.3'

services:
  master:
    image: redis:3
    networks:
      infra:
        aliases:
          - redis-master

  slave:
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    networks:
      infra:
        aliases:
          - slave

  sentinel:
    image: ignitial/sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    networks:
      infra:
        aliases:
          - sentinel

  mongo:
    image: mongo:3.6
    volumes:
      - /home/${USER}/.iio/infra/mongo:/data/db
    ports:
      - "40000:27017"
    networks:
      infra:

  minio:
    image: minio/minio
    volumes:
      - /home/${USER}/.iio/infra/minio/data:/data
      - /home/${USER}/.iio/infra/minio/config:/root/.minio
    ports:
      - "9000:9000"
    command: server /data
    networks:
      infra:

networks:
  infra:
    external: true
