referenceLib:
  endpoint: https://192.168.1.131
templates:
  js:
    app:
      material:
        default: true
        description: Vuetify based web application template
        repo: https://github.com/ignitialio/iio-app-material-template.git
        textReplacements:
          iioat: lowerCaseAppName
          "@ignitial/iio-app-material-template": lowerCaseAppName
          IgnitialIO: appName
          ignitialio: lowerCaseAppName
        filenameReplacements:
          ignitialio: lowerCaseAppName
        message: Your micro-services based application is ready
    service:
      standard:
        default: true
        description: IIO service template
        namingRules: [a-z][a-z0-9]*
        nameSuffix: -service
        repo: https://github.com/ignitialio/iio-svc-template.git
        textReplacements:
          Iiost: upperCaseAppName
          iiost: lowerCaseAppName
          "@ignitial/iio-svc": lowerCaseAppName
        filenameReplacements:
          iiost: lowerCaseAppName
          Iiost: upperCaseAppName
        message: Your Javascript Ignitial.io service is ready
  py:
    service:
      repo: https://gitlab.com/iio-core/iio-py-svc-template.git
      description: Python IIOS service template
      message: Your Python Ignitial.io service is ready
