js:
  app:
    repo: https://github.com/ignitialio/iio-app-template.git
  service:
    repo: https://github.com/ignitialio/iio-svc-template.git
  desktop:
    repo: https://gitlab.com/iio-core/electron-app-template.git
  test:
    repo: https://gitlab.com/iio-core/iio-app-nxt.git
    replacements:
      iioat: 'lowerCaseAppName'
      '@ignitial/iio-app-nxt': 'lowerCaseAppName'
      IgnitialIO: 'appName'
      ignitialio: 'lowerCaseAppName'
py:
  service:
    repo: https://gitlab.com/iio-core/iio-py-svc-template.git
