version: '3.3'

services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      infra:

  mongo:
    image: mongo:3.6
    container_name: mongo
    volumes:
      - /home/${USER}/iio-data/mongo:/data/db
    ports:
      - "40000:27017"
    networks:
      infra:

  minio:
    image: minio/minio
    container_name: minio
    volumes:
      - /home/${USER}/iio-data/minio/data:/data
      - /home/${USER}/iio-data/minio/config:/root/.minio
    ports:
      - "9000:9000"
    command: server /data
    networks:
      infra:

  dlake-toto:
    image: registry.ignitial.io/ignitial/dlake-toto:${APP_VERSION}
    container_name: dlake-toto
    volumes:
      - ${PWD}/datum:/opt/dlake/datum
    ports:
      - "20991:20991"
    environment:
      - REDIS_HOST=redis
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DBNAME=toto
      - IIOS_NAMESPACE=toto
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=20991
    networks:
      iio:
      infra:

networks:
  iio:
  infra:
    external: true
