version: '3.3'

services:
  master:
    image: redis:3
    networks:
      iio:
        aliases:
          - redis-master

  slave:
    image: redis:3
    command: redis-server --slaveof redis-master 6379
    networks:
      iio:
        aliases:
          - slave

  sentinel:
    image: ignitial/sentinel
    environment:
      - SENTINEL_DOWN_AFTER=5000
      - SENTINEL_FAILOVER=5000
    networks:
      iio:
        aliases:
          - sentinel

  mongo:
    image: mongo:3.6
    volumes:
      - /home/${USER}/iio-data/mongo:/data/db
    ports:
      - "40000:27017"
    networks:
      iio:

  minio:
    image: minio/minio
    volumes:
      - /home/${USER}/iio-data/minio/data:/data
      - /home/${USER}/iio-data/minio/config:/root/.minio
    ports:
      - "9000:9000"
    command: server /data
    networks:
      iio:

  dlake-toto:
    image: registry.ignitial.io/ignitial/dlake-toto:${APP_VERSION}
    volumes:
      - ${PWD}/datum:/opt/dlake/datum
    ports:
      - "20991:20991"
    environment:
      - REDIS_MASTER_NAME=mymaster
      - REDIS_SENTINELS=sentinel
      - MONGODB_URI=mongodb://mongo:27017
      - MONGODB_DBNAME=toto
      - IIOS_NAMESPACE=toto
      - IIOS_SERVER_HOST=0.0.0.0
      - IIOS_SERVER_PORT=20991
    networks:
      iio:

  toto:
    image: registry.ignitial.io/ignitial/toto
    volumes:
      - ${PWD}:/opt/toto
    environment:
      - IIO_SERVER_PORT=8080
      - IIOS_NAMESPACE=toto
      - MONGODB_URI=mongodb://mongo:27017
      - REDIS_MASTER_NAME=mymaster
      - REDIS_SENTINELS=sentinel
      - S3_ENDPOINT=s3.amazonaws.com
      - S3_BUCKET=636ojbq68oou95ut5ayq8yd9c9n6cm5c
      - S3_SECURE=true
      - S3_REGION=eu-west-3
      - EMAILER_SMTP_USER=support@ignitial.fr
      - EMAILER_SMTP_HOST=mail.gandi.net
      - EMAILER_SMTP_PORT=587
    secrets:
      - s3_access_key_id
      - s3_secret_access_key
      - emailer_smtp_pass
    ports:
      - "8080:8080"
    networks:
      iio:

networks:
  iio:

secrets:
  s3_access_key_id:
    external: true
  s3_secret_access_key:
    external: true
  emailer_smtp_pass:
    external: true
  mongodb_pwd:
    external: true
